hosts:
  services:
    template-service: http://localhost:8081
    template-multi-service: http://localhost:8082

spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      routes:
      - id: template-service-single
        uri: ${hosts.services.template-service}
        predicates:
        - Path=/templateservice/**
      - id: template-service-multi
        uri: ${hosts.services.template-multi-service}
        predicates:
        - Path=/templatemultiservice/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'